---
# Role tasks

- block:
    - block:
        - name: assert distribution is supported
          assert:
            that: >-
              distribution
              in check_platform_distributions.keys() | map("lower") | list
            msg: "{{ distribution }} distribution is not supported"

        - name: assert distribution version is supported
          assert:
            that: >-
              ansible_facts.distribution_version
              is version(check_platform_distributions[distribution], ">=")
            msg: >-
              {{ distribution }} distribution
              version {{ ansible_facts.distribution_version }} is not supported
      vars:
        distribution: "{{ ansible_facts.distribution | lower }}"

    - name: assert required variables are defined
      assert:
        that: >-
          lookup('vars', check_platform_variable, default="<UNDEFINED/>")
          != "<UNDEFINED/>"
        msg: "required variable {{ check_platform_variable }} is missing"
      loop: "{{ check_plaform_variables }}"
      loop_control:
        loop_var: check_platform_variable
        label: "{{ check_platform_variable }}"
  tags:
    - role::check_platform
