---
# Role tasks

- block:
    - include_tasks: check.yml
      when: >-
        lookup("dict", check_platform_distributions | default({}))
        | list
        | union(check_platform_checked_distributions | default([]))
        != check_platform_checked_distributions | default([])
        or
        check_platform_variables | default([])
        | union(check_platform_checked_variables | default([]))
        != check_platform_checked_variables | default([])
  tags:
    - role::check_platform
