---
# Undefined placeholder tasks

- name: Generate undefined value place holder
  set_fact:
    check_platform_undefined_place_holder: >-
      {{ "__check_platform_undefined_place_holder__"
         + (99999999999999999999999999999999999999999999999999
            | random
            | to_uuid) }}
  when: check_platform_undefined_place_holder is undefined
