---
# Variables check tasks

- name: Assert required variables are defined
  assert:
    that:
      - value != check_platform_undefined_place_holder
      - value is not none
    msg: "required variable {{ check_platform_variable }} is missing"
  loop: "{{ check_plaform_variables }}"
  loop_control:
    loop_var: check_platform_variable
    label: "{{ check_platform_variable }}"
  vars:
    value: >-
      {{ lookup('vars',
                check_platform_variable,
                default=check_platform_undefined_place_holder) }}

- name: Setup fact with checked variables
  set_fact:
    check_platform_checked_variables: >-
      {{ (check_platform_checked_variables | default([])
          + [ check_plaform_variables ])
         | unique }}
  when: check_plaform_variables | length > 0
